"""AstrContinuum domain package."""

from . import runtime as _runtime
from .compaction import (
    AuditedCandidate,
    CompilationCandidate,
    CompilationRequest,
    CompilerBackend,
    CompilerErrorCode,
    CompilerInvariantError,
    CompilerOutput,
    EventSegment,
    SegmentBoundaryReason,
    SegmenterConfig,
    SemanticAuditBackend,
    SemanticAuditErrorCode,
    SemanticAuditInvariantError,
    SemanticAuditReport,
    SemanticAuditRequest,
    audit_semantic,
    compile_candidate,
    segment,
    validate_candidate,
)
from .domain import (
    AnchorStatus,
    AnchorType,
    CapsuleAnchor,
    CapsuleClaim,
    CapsuleLevel,
    CapsuleQuality,
    CompactionJobEnvelope,
    CompactionJobState,
    ContextCapsuleEnvelope,
    Decision,
    Dependency,
    Entity,
    EventEnvelope,
    EventRole,
    EventType,
    PermanentFailureCode,
    PermanentValidationReport,
    SemanticAuditStatus,
    SemanticStatus,
    SessionKey,
    SnapshotAuditOutcome,
    SnapshotEnvelope,
    SnapshotState,
    SourceHook,
    validate_permanent,
)
from .models import (
    AssemblyTrace,
    AuditReport,
    Claim,
    ClaimStatus,
    ContextCapsule,
    ContextEvent,
    ExactAnchor,
    Snapshot,
)
from .runtime import (
    RUNTIME_SLOT_PRIORITY,
    CandidateBlock,
    CandidateKind,
    RequestViewErrorCode,
    RequestViewInvariantError,
    RequestViewSource,
    RetrievalConfig,
    RuntimeSlot,
    read_request_view,
    select_candidates,
)
from .storage import (
    MIGRATIONS,
    EventIdentityConflict,
    IdempotencyConflict,
    JobTransitionError,
    Migration,
    MigrationApplyError,
    MigrationChecksumError,
    MigrationError,
    MigrationPlanError,
    PublicationRejected,
    PublishOutcome,
    PublishResult,
    RepositoryConflict,
    RepositoryError,
    RepositoryInvariantError,
    RequestView,
    SessionIdentityConflict,
    SnapshotCapsuleMembership,
    SQLiteConnectionFactory,
    SQLiteMigrator,
    SQLiteRepository,
    StaleLeaseError,
)

RuntimeAssemblyMode = _runtime.AssemblyMode
RuntimeAssemblyResult = _runtime.AssemblyResult
RuntimeAssemblyTrace = _runtime.AssemblyTrace
RuntimeBlockRejection = _runtime.BlockRejection
RuntimeBlockSelection = _runtime.BlockSelection
RuntimeBudgetConfig = _runtime.BudgetConfig
RuntimeBudgetInvariantError = _runtime.BudgetInvariantError
RuntimeTokenCounter = _runtime.TokenCounter
RuntimeUtf8ByteTokenCounter = _runtime.Utf8ByteTokenCounter
runtime_assemble = _runtime.assemble

__all__ = [
    "MIGRATIONS",
    "RUNTIME_SLOT_PRIORITY",
    "AnchorStatus",
    "AnchorType",
    "AssemblyTrace",
    "AuditReport",
    "AuditedCandidate",
    "CandidateBlock",
    "CandidateKind",
    "CapsuleAnchor",
    "CapsuleClaim",
    "CapsuleLevel",
    "CapsuleQuality",
    "Claim",
    "ClaimStatus",
    "CompactionJobEnvelope",
    "CompactionJobState",
    "CompilationCandidate",
    "CompilationRequest",
    "CompilerBackend",
    "CompilerErrorCode",
    "CompilerInvariantError",
    "CompilerOutput",
    "ContextCapsule",
    "ContextCapsuleEnvelope",
    "ContextEvent",
    "Decision",
    "Dependency",
    "Entity",
    "EventEnvelope",
    "EventIdentityConflict",
    "EventRole",
    "EventSegment",
    "EventType",
    "ExactAnchor",
    "IdempotencyConflict",
    "JobTransitionError",
    "Migration",
    "MigrationApplyError",
    "MigrationChecksumError",
    "MigrationError",
    "MigrationPlanError",
    "PermanentFailureCode",
    "PermanentValidationReport",
    "PublicationRejected",
    "PublishOutcome",
    "PublishResult",
    "RepositoryConflict",
    "RepositoryError",
    "RepositoryInvariantError",
    "RequestView",
    "RequestViewErrorCode",
    "RequestViewInvariantError",
    "RequestViewSource",
    "RetrievalConfig",
    "RuntimeAssemblyMode",
    "RuntimeAssemblyResult",
    "RuntimeAssemblyTrace",
    "RuntimeBlockRejection",
    "RuntimeBlockSelection",
    "RuntimeBudgetConfig",
    "RuntimeBudgetInvariantError",
    "RuntimeSlot",
    "RuntimeTokenCounter",
    "RuntimeUtf8ByteTokenCounter",
    "SQLiteConnectionFactory",
    "SQLiteMigrator",
    "SQLiteRepository",
    "SegmentBoundaryReason",
    "SegmenterConfig",
    "SemanticAuditBackend",
    "SemanticAuditErrorCode",
    "SemanticAuditInvariantError",
    "SemanticAuditReport",
    "SemanticAuditRequest",
    "SemanticAuditStatus",
    "SemanticStatus",
    "SessionIdentityConflict",
    "SessionKey",
    "Snapshot",
    "SnapshotAuditOutcome",
    "SnapshotCapsuleMembership",
    "SnapshotEnvelope",
    "SnapshotState",
    "SourceHook",
    "StaleLeaseError",
    "audit_semantic",
    "compile_candidate",
    "read_request_view",
    "runtime_assemble",
    "segment",
    "select_candidates",
    "validate_candidate",
    "validate_permanent",
]
