"""Host adapters for AstrContinuum."""

from .astrbot import (
    AdapterErrorCode,
    AdapterFault,
    AdapterStage,
    AstrBotAdapterError,
    AstrBotHookBridge,
    ContextEngineMode,
    DeterministicEventIdentity,
    HostTurnIdentity,
    LiveContextTrace,
    PreparedRequest,
    ProjectionBuild,
    ProjectionFactory,
    build_projection_objects,
    canonical_tool_metadata,
    deterministic_event_identity,
    estimate_opaque_token_cost,
    extract_host_session_key,
    extract_host_turn_identity,
    projection_factory_from_user_message,
    select_projection_boundaries,
)
from .sylanne import SylanneAdapter

__all__ = [
    "AdapterErrorCode",
    "AdapterFault",
    "AdapterStage",
    "AstrBotAdapterError",
    "AstrBotHookBridge",
    "ContextEngineMode",
    "DeterministicEventIdentity",
    "HostTurnIdentity",
    "LiveContextTrace",
    "PreparedRequest",
    "ProjectionBuild",
    "ProjectionFactory",
    "SylanneAdapter",
    "build_projection_objects",
    "canonical_tool_metadata",
    "deterministic_event_identity",
    "estimate_opaque_token_cost",
    "extract_host_session_key",
    "extract_host_turn_identity",
    "projection_factory_from_user_message",
    "select_projection_boundaries",
]
