"""Durable SQLite foundations for AstrContinuum."""

from .crypto import (
    SecureCodec,
    SecurityErrorCode,
    StorageSecurityError,
    encode_key_text,
    key_id_for,
    parse_key_text,
)
from .migrations import (
    MIGRATIONS,
    Migration,
    MigrationApplyError,
    MigrationChecksumError,
    MigrationError,
    MigrationPlanError,
    SQLiteMigrator,
)
from .repository import (
    EventIdentityConflict,
    IdempotencyConflict,
    JobTransitionError,
    PublicationRejected,
    PublishOutcome,
    PublishResult,
    RepositoryConflict,
    RepositoryError,
    RepositoryInvariantError,
    RequestView,
    SessionIdentityConflict,
    SnapshotCapsuleMembership,
    SQLiteRepository,
    StaleLeaseError,
)
from .security import (
    GeneratedKeyFile,
    KeyMaterial,
    KeySource,
    ResolvedKeyMaterial,
    StorageMaintenanceState,
    StorageSecurityActivation,
    activate_storage_security,
    fingerprint_key_file,
    generate_key_file,
    resolve_key_material,
)
from .sqlite import (
    DATABASE_FILENAME,
    DEFAULT_BUSY_TIMEOUT_MS,
    MAX_BUSY_TIMEOUT_MS,
    SQLiteConnectionFactory,
)

__all__ = [
    "DATABASE_FILENAME",
    "DEFAULT_BUSY_TIMEOUT_MS",
    "MAX_BUSY_TIMEOUT_MS",
    "MIGRATIONS",
    "EventIdentityConflict",
    "GeneratedKeyFile",
    "IdempotencyConflict",
    "JobTransitionError",
    "KeyMaterial",
    "KeySource",
    "Migration",
    "MigrationApplyError",
    "MigrationChecksumError",
    "MigrationError",
    "MigrationPlanError",
    "PublicationRejected",
    "PublishOutcome",
    "PublishResult",
    "RepositoryConflict",
    "RepositoryError",
    "RepositoryInvariantError",
    "RequestView",
    "ResolvedKeyMaterial",
    "SQLiteConnectionFactory",
    "SQLiteMigrator",
    "SQLiteRepository",
    "SecureCodec",
    "SecurityErrorCode",
    "SessionIdentityConflict",
    "SnapshotCapsuleMembership",
    "StaleLeaseError",
    "StorageMaintenanceState",
    "StorageSecurityActivation",
    "StorageSecurityError",
    "activate_storage_security",
    "encode_key_text",
    "fingerprint_key_file",
    "generate_key_file",
    "key_id_for",
    "parse_key_text",
    "resolve_key_material",
]
